export const TYPE = {
  GET_LIST_TODO: 'GET_LIST_TODO',
  GET_LIST_TODO_SUCCESS: 'GET_LIST_TODO_SUCCESS',
  GET_LIST_TODO_ERROR: 'GET_LIST_TODO_ERROR',
  SET_SELECTED_TODO: 'SET_SELECTED_TODO',
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
};
